# Generated by Django 6.0.1 on 2026-02-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='related_webinar',
            field=models.ForeignKey(blank=True, help_text='Generic webinar reference for any notification type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to='webinars.event'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('upcoming_webinar', 'Upcoming Webinar'), ('new_recording', 'New Recording'), ('live_started', 'Live Session Started'), ('live_ended', 'Live Session Ended'), ('registration_approved', 'Registration Approved'), ('system', 'System Notification')], max_length=30),
        ),
    ]
