# Generated by Django 6.0 on 2026-01-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_duration_event_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD. Set to 0 for free.', max_digits=10),
        ),
    ]
