# Generated by Django 6.0 on 2026-01-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_announcement_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='live_stream_url',
            field=models.URLField(blank=True, help_text='URL for live stream embed (e.g., YouTube, Vimeo)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='manual_status',
            field=models.CharField(blank=True, choices=[('', 'Auto'), ('completed', 'Completed')], default='', help_text='Override automatic status calculation', max_length=20),
        ),
    ]
