# Generated by Django 6.0.1 on 2026-03-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0002_session_lifecycle_and_participants'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='livesession',
            new_name='live_sessio_webinar_37d63f_idx',
            old_name='live_sessio_webinar_idx',
        ),
        migrations.RenameIndex(
            model_name='livesession',
            new_name='live_sessio_is_acti_894076_idx',
            old_name='live_sessio_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='livesessionparticipant',
            new_name='live_sessio_session_12972b_idx',
            old_name='live_sessio_session_user_idx',
        ),
    ]
