# Generated by Django 6.0.1 on 2026-02-19 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webinars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_link', models.URLField(help_text='Link to the recording (YouTube, Vimeo, etc.)')),
                ('title', models.CharField(blank=True, help_text='Optional custom title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Recording duration in minutes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, help_text='Make recording publicly available')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='webinars.event')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recording',
                'verbose_name_plural': 'Recordings',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['event'], name='recordings__event_i_091902_idx'), models.Index(fields=['is_public', 'uploaded_at'], name='recordings__is_publ_d2ae2b_idx')],
            },
        ),
    ]
