# Generated by Django 6.0.1 on 2026-02-19 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD. Set to 0 for free.', max_digits=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='webinar_thumbnails/')),
                ('live_stream_url', models.URLField(blank=True, help_text='URL for live stream embed (e.g., YouTube, Vimeo)', null=True)),
                ('manual_status', models.CharField(blank=True, choices=[('', 'Auto'), ('completed', 'Completed')], default='', help_text='Override automatic status calculation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webinar',
                'verbose_name_plural': 'Webinars',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date', 'time'], name='webinars_ev_date_567368_idx'), models.Index(fields=['organizer'], name='webinars_ev_organiz_0ba62d_idx')],
            },
        ),
    ]
